### ISSUE TITLE
Driver should listen to local unix socket to provide a way for GUI to send through USB commands

### ISSUE THREAD

**Issue by kurikaesu** [kurikaesu/xp-pen-userland#2]
For some tablets like the XP-Pen Deco Pro (S/M) they have a flag that can be set on the tablet itself to switch the functionality of one of the hardware features by sending a message to the device.

Currently there is no way to do this while the driver is running and the only way to influence the driver during runtime is through sending it a SIGHUP which reloads the configuration files.

The idea behind the socket is that the driver will listen for different commands such as reloading configuration or sending USB packets to a specific device.

There are a few other benefits of having the local socket such as:
- Knowing that the driver is actually running.
- In cases where the driver needs to send some information back to the configuration GUI. (Though I can't think of any situation where this would happen yet)

**Comment by kanashimia** [comment]
> Though I can't think of any situation where this would happen yet

Getting current touch wheel mode (mouse, wheel) getting current led brightness config. 

Also we could read and send back whole configuration through the socket, instead of touching config file and sending SIGHUP, not sure if this is useful tho.
